#ifndef QDRANT_EDGE_FFI_H
#define QDRANT_EDGE_FFI_H

/* This file was auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an EdgeShard, protected by a Mutex for thread safety.
 */
typedef struct QeShardHandle QeShardHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new shard. `config_json` is a JSON-serialized EdgeConfig.
 * Returns an opaque handle, or null on error (check `qe_last_error`).
 */
struct QeShardHandle *qe_shard_create(const char *path, const char *config_json);

/**
 * Load an existing shard from disk. `config_json` can be empty for default.
 */
struct QeShardHandle *qe_shard_load(const char *path, const char *config_json);

/**
 * Close and free a shard handle. After this call the handle is invalid.
 */
void qe_shard_close(struct QeShardHandle *handle);

/**
 * Flush pending writes to disk.
 */
void qe_shard_flush(struct QeShardHandle *handle);

/**
 * Run optimizers (merge segments, build HNSW indexes).
 * Returns 1 if something was optimized, 0 if already optimal, -1 on error.
 */
int32_t qe_shard_optimize(struct QeShardHandle *handle);

/**
 * Upsert points. `points_json` is a JSON array of PointInput objects.
 * Returns 0 on success, -1 on error.
 */
int32_t qe_shard_upsert(struct QeShardHandle *handle, const char *points_json);

/**
 * Delete points by IDs. `ids_json` is a JSON array of u64 IDs.
 * Returns 0 on success, -1 on error.
 */
int32_t qe_shard_delete_points(struct QeShardHandle *handle, const char *ids_json);

/**
 * Set payload on a point.
 */
int32_t qe_shard_set_payload(struct QeShardHandle *handle,
                             uint64_t point_id,
                             const char *payload_json);

/**
 * Delete payload keys from a point.
 */
int32_t qe_shard_delete_payload(struct QeShardHandle *handle,
                                uint64_t point_id,
                                const char *keys_json);

/**
 * Create a field index.
 */
int32_t qe_shard_create_field_index(struct QeShardHandle *handle,
                                    const char *field_name,
                                    const char *field_type);

/**
 * Delete a field index.
 */
int32_t qe_shard_delete_field_index(struct QeShardHandle *handle, const char *field_name);

/**
 * Search for nearest neighbors. Returns JSON string with results.
 * The caller must free the returned string with `qe_free_string`.
 */
char *qe_shard_search(struct QeShardHandle *handle, const char *request_json);

/**
 * Full query with prefetches and fusion. Returns JSON string.
 * The caller must free the returned string with `qe_free_string`.
 */
char *qe_shard_query(struct QeShardHandle *handle, const char *request_json);

/**
 * Retrieve specific points by IDs. Returns JSON string.
 */
char *qe_shard_retrieve(struct QeShardHandle *handle,
                        const char *ids_json,
                        bool with_payload,
                        bool with_vector);

/**
 * Scroll through points. Returns JSON string with { points, next_offset }.
 */
char *qe_shard_scroll(struct QeShardHandle *handle, const char *request_json);

/**
 * Count points, optionally with a filter. Returns count or -1 on error.
 */
int64_t qe_shard_count(struct QeShardHandle *handle, const char *filter_json);

/**
 * Get shard info. Returns JSON string.
 */
char *qe_shard_info(struct QeShardHandle *handle);

/**
 * Free a string returned by any qe_ function.
 */
void qe_free_string(char *ptr);

/**
 * Get the last error message. Returns null if no error. Caller must free with qe_free_string.
 */
char *qe_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QDRANT_EDGE_FFI_H */
