#ifndef QDRANT_EDGE_FFI_H
#define QDRANT_EDGE_FFI_H

/* This file was auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an `EdgeBm25` model.
 */
typedef struct QeBm25Handle QeBm25Handle;

/**
 * Opaque handle to an `EdgeShard`, protected by a Mutex for thread safety.
 */
typedef struct QeShardHandle QeShardHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Construct a BM25 embedder from a JSON `EdgeBm25Config`. Empty input uses defaults.
 * Returns an opaque handle, or null on error (check `qe_last_error`).
 */
struct QeBm25Handle *qe_bm25_create(const char *config_json);

/**
 * Free a BM25 handle.
 */
void qe_bm25_destroy(struct QeBm25Handle *handle);

/**
 * Embed a query: each unique token weighted `1.0`.
 * Returns JSON `{ indices: number[], values: number[] }`, or null on error.
 */
char *qe_bm25_embed_query(struct QeBm25Handle *handle, const char *text);

/**
 * Embed a document: each unique token weighted by the BM25 TF formula.
 * Returns JSON `{ indices: number[], values: number[] }`, or null on error.
 */
char *qe_bm25_embed_document(struct QeBm25Handle *handle, const char *text);

/**
 * Set the global HNSW config and persist. Returns 0/-1.
 */
int32_t qe_shard_set_hnsw_config(struct QeShardHandle *handle, const char *config_json);

/**
 * Set the HNSW config for a single named vector and persist. Returns 0/-1.
 */
int32_t qe_shard_set_vector_hnsw_config(struct QeShardHandle *handle,
                                        const char *vector_name,
                                        const char *config_json);

/**
 * Set the optimizers config and persist. Returns 0/-1.
 */
int32_t qe_shard_set_optimizers_config(struct QeShardHandle *handle, const char *config_json);

/**
 * Add a new named vector slot. `op_json` is the `CreateVectorName` inner shape
 * `{"vector_name": "...", "config": { "dense": { ... } | "sparse": { ... } }}`.
 * Returns 0/-1.
 */
int32_t qe_shard_create_vector_name(struct QeShardHandle *handle, const char *op_json);

/**
 * Delete a named vector slot. Returns 0/-1.
 */
int32_t qe_shard_delete_vector_name(struct QeShardHandle *handle, const char *vector_name);

/**
 * Get the last error message. Returns null if no error.
 * Caller must free the returned string with `qe_free_string`.
 */
char *qe_last_error(void);

/**
 * Count points per unique value of the requested payload key.
 * Returns JSON `{ hits: [{ value, count }] }`, or null on error.
 */
char *qe_shard_facet(struct QeShardHandle *handle, const char *request_json);

/**
 * Free a string returned by any `qe_*` function.
 */
void qe_free_string(char *ptr);

/**
 * Create a field index.
 */
int32_t qe_shard_create_field_index(struct QeShardHandle *handle,
                                    const char *field_name,
                                    const char *field_type);

/**
 * Delete a field index.
 */
int32_t qe_shard_delete_field_index(struct QeShardHandle *handle, const char *field_name);

/**
 * Group query results by a payload field. Returns a JSON array of
 * `{ key, hits }` groups, or `null` on error.
 */
char *qe_shard_query_groups(struct QeShardHandle *handle, const char *request_json);

/**
 * Get shard info. Returns a JSON object, or `null` on error.
 */
char *qe_shard_info(struct QeShardHandle *handle);

/**
 * Create a new shard. `config_json` is a JSON-serialized `EdgeConfig`.
 * Returns an opaque handle, or null on error (check `qe_last_error`).
 */
struct QeShardHandle *qe_shard_create(const char *path, const char *config_json);

/**
 * Load an existing shard from disk. `config_json` can be empty for the stored default.
 */
struct QeShardHandle *qe_shard_load(const char *path, const char *config_json);

/**
 * Close and free a shard handle. After this call the handle is invalid.
 */
void qe_shard_close(struct QeShardHandle *handle);

/**
 * Flush pending writes to disk. Returns 0/-1.
 */
int32_t qe_shard_flush(struct QeShardHandle *handle);

/**
 * Run optimizers (merge segments, build HNSW indexes).
 * Returns 1 if something was optimized, 0 if already optimal, -1 on error.
 */
int32_t qe_shard_optimize(struct QeShardHandle *handle);

/**
 * Pairwise distance matrix over a random sample of points. Returns JSON
 * `{ sample_ids, nearests }` where `nearests[i]` are the neighbours of
 * `sample_ids[i]` within the sample, or `null` on error.
 */
char *qe_shard_search_matrix(struct QeShardHandle *handle, const char *request_json);

/**
 * Set (merge) payload fields. `op_json`: `{ payload, points?, filter?, key? }`.
 */
int32_t qe_shard_set_payload(struct QeShardHandle *handle, const char *op_json);

/**
 * Overwrite payload entirely. Same JSON shape as set_payload.
 */
int32_t qe_shard_overwrite_payload(struct QeShardHandle *handle, const char *op_json);

/**
 * Delete specific payload keys. `op_json`: `{ keys, points?, filter? }`.
 */
int32_t qe_shard_delete_payload(struct QeShardHandle *handle, const char *op_json);

/**
 * Clear all payload from a set of points or by filter.
 * `target_json`: `{ points: [...] }` OR `{ filter: ... }`.
 */
int32_t qe_shard_clear_payload(struct QeShardHandle *handle, const char *target_json);

/**
 * Upsert points. `points_json` is a JSON array of `PointInput` objects.
 * Returns 0 on success, -1 on error.
 */
int32_t qe_shard_upsert(struct QeShardHandle *handle, const char *points_json);

/**
 * Delete points by IDs. `ids_json` is a JSON array; each element is a u64 or
 * a UUID string. Returns 0 on success, -1 on error.
 */
int32_t qe_shard_delete_points(struct QeShardHandle *handle, const char *ids_json);

/**
 * Retrieve specific points by IDs. Returns JSON, or `null` on error.
 */
char *qe_shard_retrieve(struct QeShardHandle *handle,
                        const char *ids_json,
                        bool with_payload,
                        bool with_vector);

/**
 * Scroll through points. Returns JSON `{ points, next_offset }`, or `null` on error.
 */
char *qe_shard_scroll(struct QeShardHandle *handle, const char *request_json);

/**
 * Count points, optionally with a filter. Returns count or `-1` on error.
 */
int64_t qe_shard_count(struct QeShardHandle *handle, const char *filter_json);

/**
 * Nearest-neighbor search. Returns a JSON array of scored points, or `null` on error.
 * The caller must free the returned string with `qe_free_string`.
 */
char *qe_shard_search(struct QeShardHandle *handle, const char *request_json);

/**
 * Full query with prefetches and fusion. Returns a JSON array of scored points,
 * or `null` on error. The caller must free the returned string with `qe_free_string`.
 */
char *qe_shard_query(struct QeShardHandle *handle, const char *request_json);

/**
 * Read this shard's snapshot manifest. Returns JSON, or null on error.
 */
char *qe_shard_snapshot_manifest(struct QeShardHandle *handle);

/**
 * Unpack a snapshot archive into a directory. Returns 0 on success, -1 on error.
 */
int32_t qe_unpack_snapshot(const char *snapshot_path, const char *target_path);

/**
 * Recover a shard from a partial snapshot. Both manifests are JSON. Returns
 * a new shard handle (the supplied `shard_path` becomes the live shard), or
 * null on error.
 */
struct QeShardHandle *qe_recover_partial_snapshot(const char *shard_path,
                                                  const char *current_manifest_json,
                                                  const char *snapshot_path,
                                                  const char *snapshot_manifest_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QDRANT_EDGE_FFI_H */
